### ISSUE TITLE
Check network on wallet connect

### ISSUE THREAD

**Issue by ialberquilla** [nevermined-io/defi-marketplace#212]
## Is your feature request related to a problem? Please describe.
When the wallet is connected to the site, the user can have an incorrect network selected and this will drive to parts of the web that won't show properly. 

## Describe the solution you'd like
When the wallet it's connected, or the user does any change in the wallet, the web should check that the network selected in the wallet is correct (mumba, matic...) in other case, show a popup to the user, that can be disabled,  asking to switch the network. This pop up should suggest connecting to the correct network as is done in the shopping cart. 

The pop should follow the style of the others poo ups in the site. 

![image](https://user-images.githubusercontent.com/974720/159176756-269e56eb-c5db-4f53-9c42-f9640c0b3b21.png)

With a warning icon, a text asking to change the network and a button to switch the network automatically in the wallet.

**Comment by fabriziogianni7** [comment]
@ialberquilla @aaitor we still want this?

**Comment by fabriziogianni7** [comment]
Solve the provider issue and ask to change the network only at purchase stge
