### ISSUE TITLE
Show popup on a bundle download

### ISSUE THREAD

**Issue by ialberquilla** [nevermined-io/defi-marketplace#214]
## Is your feature request related to a problem? Please describe.
When a user has already purchased a bundle and wants to download it again from the profile page, there is an icon to download it. This icon opens metamask to sign a message, but there is not any feedback to the user to let them know that the assets will be retrieved and this will take some time. 

## Describe the solution you'd like
A pop up similar that the one that is displayed on the bundle creation should be shown, to let the users know that this action is required and will take some time, (Changing the purchase successful title) 

![image](https://user-images.githubusercontent.com/974720/159177432-9df1c02e-41fe-4760-8f68-091eb224d8f6.png)

**Comment by fabriziogianni7** [comment]
closes #214
