### ISSUE TITLE
Subscription purchase flow

### ISSUE THREAD

**Issue by ialberquilla** [nevermined-io/defi-marketplace#321]
- [x] Create subscription page desing
- [x] Defin susbscription purchase flow

**Comment by jjoyce86** [comment]
@josepablofm78 Hey could you drop some screen shots in here of the pop-ups please?

**Comment by josepablofm78** [comment]
![popup1](https://user-images.githubusercontent.com/45420891/186425719-4566bf88-0ce9-4bfd-9ac0-162cca2a35d6.png)
![popup2](https://user-images.githubusercontent.com/45420891/186425740-46d8433c-f3a1-4fce-8aaf-771595af6878.png)
![popup3](https://user-images.githubusercontent.com/45420891/186425759-e2b60958-1ae4-4098-9c8c-71b6466889f2.png)
![popup5](https://user-images.githubusercontent.com/45420891/186425772-4b3d2052-c9c1-4cb0-9c69-95d860e095da.png)

**Comment by josepablofm78** [comment]
here you have them @jjoyce86
