### ISSUE TITLE
Marketplace asset listing

### ISSUE THREAD

**Issue by ialberquilla** [nevermined-io/defi-marketplace#322]
Review marketplace asset listing 

- [x]  Include a field in the table to show the asset tier
- [x] Review the icons to let the user know if an asset is already purchased / is owned by the user / is published by the user...
- [x] Specify the list of fields we want to show in the listing (NVM)
- [x] Specify filtering (NVM)

**Comment by jjoyce86** [comment]
@ialberquilla Have the list of fields been decided on here?

**Comment by josepablofm78** [comment]
List of fields: Asset Name - Date - Subscription level ( as badge or icon) - Type (Dataset, Report, Notebook, Dashboard) -Category - Network
Filters: Current ones + Type + Subscription
