### ISSUE TITLE
Add missing env variables

### ISSUE THREAD

**Issue by aaitor** [nevermined-io/defi-marketplace#330]

**Comment by josepablofm78** [comment]
Missing env variables for the frontend:
NEXT_PUBLIC_GATEWAY_ADDRESS
NEXT_PUBLIC_SECRET_STORE_URI (default to localhost. Is this still needed?)
NEXT_PUBLIC_IPFS_GATEWAY_URI
NEXT_PUBLIC_CORRECT_NETWORK_ID
NEXT_PUBLIC_CORRECT_NETWORK_NAME

**Comment by josepablofm78** [comment]
New ones  needed for the subscription tiers:
NEXT_PUBLIC_DID_NFT_TIER1
NEXT_PUBLIC_NFT_ADDRESS_TIER1
NEXT_PUBLIC_DID_NFT_TIER2
NEXT_PUBLIC_NFT_ADDRESS_TIER2
NEXT_PUBLIC_DID_NFT_TIER3
NEXT_PUBLIC_NFT_ADDRESS_TIER3
NEXT_PUBLIC_NFT_TIERS_HOLDER
NEXT_PUBLIC_NFT_TIERS_AMOUNT
NEXT_PUBLIC_SUBSCRIPTION_DURATION_IN_BLOCKS
NEXT_PUBLIC_NETWORK_BLOCK_INTERVAL

**Comment by josepablofm78** [comment]
env defined in config but not used:
NEXT_PUBLIC_ANALYTICS_ID
NEXT_PUBLIC_SHOW_CHANNELS
NEXT_PUBLIC_IPFS_NODE_URI
NEXT_PUBLIC_CORRECT_NETWORK_URL
