### ISSUE TITLE
Asset's Provenance in Subscription model

### ISSUE THREAD

**Issue by josepablofm78** [nevermined-io/defi-marketplace#363]

**Comment by r-marques** [comment]
https://api.thegraph.com/subgraphs/name/nevermined-io/commonmumbaiv2didregistry/graphql?query=query+Provenance+%7B%0A++useds+%7B%0A++++id%0A++++_did%0A++++_activityId%0A++++__typename%0A++++_attributes%0A++%7D%0A%7D
