### ISSUE TITLE
Check subscription label in account details

### ISSUE THREAD

**Issue by ialberquilla** [nevermined-io/defi-marketplace#378]
We have changed how the subscription info is shown in the dashboard. showing a number didn't make a lot of sense, so we showing now a label with the name of the subscription.

Maybe @jjoyce86 you can figure out how to make it look a little bit better than now. Maybe increasing the size of the font could be enough

**Comment by josepablofm78** [comment]
![Image](https://user-images.githubusercontent.com/45420891/191194381-da10b0d9-360c-4fa8-a4ed-e7abbd3901b4.png)

**Comment by josepablofm78** [comment]
![Image](https://user-images.githubusercontent.com/45420891/191195114-501cc8d4-23ff-47fa-8726-a16bf6abeff3.png)

**Comment by jjoyce86** [comment]
@josepablofm78 I'm thinking maybe something like this if it's not too much work. Adding in subscription tag style and the changing background colour. What do you think?
<img width="633" alt="Screenshot 2022-09-20 at 10 48 50" src="https://user-images.githubusercontent.com/110973653/191227372-db300acc-8fcf-4d22-bfbf-636d6c8003bc.png">

**Comment by ialberquilla** [comment]
@jjoyce86 Is it possible to change the colors of all the sections? not only subscription? I see it like this specific KPI is more important or different. Also, consider that the user can have no subscription, so the tag would have no icon.

**Comment by josepablofm78** [comment]
@jjoyce86 we have discussed this internally and we agreed it looks good as it is. Only thing would be to add a label or icon to indicate the user has not a current subscription

**Comment by jjoyce86** [comment]
![Image](https://user-images.githubusercontent.com/110973653/192462829-dc407ac3-734b-47dd-a661-143a1643adc6.png)
