### ISSUE TITLE
Design for Landing page

### ISSUE THREAD

**Issue by josepablofm78** [nevermined-io/defi-marketplace#382]
we are still showing the old landing page, mentioning the purchase flow

**Comment by josepablofm78** [comment]
![Image](https://user-images.githubusercontent.com/45420891/189866201-82a5ed00-120c-4358-bbe3-6efbb3acdb6f.png)

**Comment by josepablofm78** [comment]
@jjoyce86  could you please take a look at this?

**Comment by jjoyce86** [comment]
@josepablofm78 Hi, we might be better just hiding this section for now. It would require some new copy I think for the purchasing journey how works with the subscriptions. The icons will also probably need to change. We'll probably need to add the redesign of this section as a separate text.

**Comment by josepablofm78** [comment]
@jjoyce86 we were thinking that we only need a few small changes for the first iteration, and then we can work in a more complete redesign, in the same line you comment.

I will comment over the original design of the landing page on figma

**Comment by jjoyce86** [comment]
Updated the how it works here 

![Image](https://user-images.githubusercontent.com/110973653/192462780-6070f983-48a3-4382-9458-d976d2381411.png)
