### ISSUE TITLE
Visiting the marketplace without MetaMask installed should not fail to load the page

### ISSUE THREAD

**Issue by simodrws** [nevermined-io/defi-marketplace#43]
## Describe the bug
When you visit the marketplace page without MetaMask installed, all that is loaded is the background. The console prints a lot of errors. 

##  To Reproduce
1. Visit https://defi.mumbai.nevermined.rocks/ without MetaMask installed
2. Look in the console.

## Expected behavior
There should be information for the visitor to install MetaMask and then reopen the page.

## Screenshots

https://user-images.githubusercontent.com/25478125/142182339-9415145d-ffb8-4790-8e05-0dedb19511ab.mp4

**Comment by ssallam** [comment]
I'm looking at using this as part of the solution: https://github.com/Web3Modal/web3modal

**Comment by ssallam** [comment]
https://github.com/Web3Modal/web3modal

**Comment by ssallam** [comment]
https://github.com/nevermined-io/defi-marketplace/issues/39

**Comment by ialberquilla** [comment]
This is fixed here @ssallam https://github.com/nevermined-io/defi-marketplace/pull/82

You can test it opening the site in a private browser
